[theme]
primaryColor = "#3B82F6"             # Tailwind's blue-500
backgroundColor = "#1F2937"          # Tailwind's gray-900
secondaryBackgroundColor = "#2D3748" # Tailwind's gray-800 for the sidebar
textColor = "#FFFFFF"
font = "sans serif"